#! /bin/sh

# Autostart
picom -b &
xwallpaper --output DP-1 --stretch ~/Pictures/Wallpapers/wallpaper0002.jpg &
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sxhkd &
~/.local/bin/launch.sh &

# Monitors
bspc monitor DP-1 -d 1 2 3 4 5 6 7 8

bspc config remove_disabled_monitors true

# Windows
bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

## Colors
bspc config focused_border_color "#5294E2"

# Application Rules
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a firefox desktop='^3'
bspc rule -a mpv desktop='^6' state=floating follow=on
bspc rule -a Sxiv desktop='^5' state=floating follow=on
bspc rule -a PCSX2 desktop='^8' state=floating follow=on
bspc rule -a Pcmanfm state=floating
bspc rule -a VirtualBox desktop='^7' state=floating follow=on
bspc rule -a Lxtask state=floating
